### ISSUE TITLE
Not working for HTML5 output

### ISSUE THREAD

**Issue by fkohrt** [NMarkgraf/typography.py#6]
It appears this filter does not work for HTML5 output. Using the following `Test.md`...

```md
# Überschrift

Dies ist z.B. ein Test. U.a. ist es auch eine Demonstration.
```

...and the following command...

```bash
pandoc --to=html5 --output=Test.html --filter=typography.py Test.md
```

...yields...

```html
<h1 id="überschrift">Überschrift</h1>
<p>Dies ist z.B. ein Test. U.a. ist es auch eine Demonstration.</p>
```

**Comment by NMarkgraf** [comment]
Well, Florian, this is simple. - I will fix this asap. HTML5 was not on the internal "output is html" list. ;-)

**Comment by NMarkgraf** [comment]
Done. - If any problems occur, please reopen this issue or a new one! -- Thanks!

**Comment by fkohrt** [comment]
This fixes it! Now I noticed that there are several other formats where this should work, including:

- `html4`
- `slideous`
- `slidy`
- `dzslides`
- `revealjs`
- `s5`

**Comment by NMarkgraf** [comment]
Okay. - Done. :-)
